CREATE TABLE CLIENTES(
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL PRIMARY KEY,
DATA_NASCIMENTO DATE,
TELEFONE VARCHAR(11) NOT NULL,
EMAIL VARCHAR(30) NOT NULL
);

CREATE TABLE LIVROS(
NOME VARCHAR(50) NOT NULL,
CODIGO_ID INTEGER NOT NULL PRIMARY KEY,
AUTOR VARCHAR(30) NOT NULL,
DATA_LANCAMENTO DATE NOT NULL,
QUANTIDADE_CADASTRADA INTEGER NOT NULL
);

CREATE TABLE EMPRESTIMO(
QUANTIDADE_EMPRESTADA INTEGER,
ID_IMPRESTIMO SERIAL NOT NULL PRIM
);
